language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - 0.7
    - 1.0
# This is left as an example for the next big version switch.
# matrix:
#     allow_failures:
#         - julia: 0.7
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("JuMP")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("JuMP")); include(joinpath("docs", "make.jl"))'
